source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

gem 'cocoapods', '~> 1.13'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'
# json-schema used during CocoaPods/codegen still passes quirks_mode.
# JSON 3 rejects that keyword; keep the compatible existing transitive gem.
gem 'json', '>= 2.10.2', '< 3.0'
