import type { ImageRoomDefinition } from './ImageRoomDefinition'

type CuratedRoomId = 'sports-center' | 'auditorium'
const curatedRoom = (room: ImageRoomDefinition): ImageRoomDefinition => Object.freeze(room)

export const CURATED_CAMPUS_ROOMS: Readonly<Record<CuratedRoomId, ImageRoomDefinition>> = Object.freeze({
  'sports-center': curatedRoom({
    id: 'sports-center',
    title: 'Sports Center',
    spawnNodeId: 'entrance',
    image: {
      url: 'assets/rooms/tedu-sports-center-wide.png',
      width: 1672,
      height: 941,
      sha256: '4ad9bb8bbeb6a2a5ff55d15ef4a99b25872f4092d2fbf1ddc5e371f0c12e9313',
    },
    nodes: [
      { id: 'entrance', x: 84, y: 94, z: 0 },
      { id: 'front-left', x: 32, y: 82, z: 0 },
      { id: 'front-right', x: 72, y: 82, z: 0 },
      { id: 'center-floor', x: 76, y: 70, z: 0 },
      { id: 'dumbbell-aisle', x: 20, y: 61, z: 0 },
      { id: 'bench-left', x: 38, y: 53, z: 0 },
      { id: 'bench-right', x: 62, y: 52, z: 0 },
      { id: 'treadmill-aisle', x: 32, y: 36, z: 0 },
      { id: 'machine-aisle', x: 68, y: 35, z: 0 },
    ],
    edges: [
      { from: 'entrance', to: 'front-right', kind: 'walk' },
      { from: 'front-left', to: 'dumbbell-aisle', kind: 'walk' },
      { from: 'front-left', to: 'center-floor', kind: 'walk' },
      { from: 'front-right', to: 'center-floor', kind: 'walk' },
      { from: 'center-floor', to: 'bench-left', kind: 'walk' },
      { from: 'center-floor', to: 'bench-right', kind: 'walk' },
      { from: 'bench-left', to: 'treadmill-aisle', kind: 'walk' },
      { from: 'bench-right', to: 'machine-aisle', kind: 'walk' },
      { from: 'treadmill-aisle', to: 'machine-aisle', kind: 'walk' },
    ],
    seats: [],
    occluders: [],
    actors: {},
  }),
  auditorium: curatedRoom({
    id: 'auditorium',
    title: 'Fatma–Semih Akbil Auditorium',
    spawnNodeId: 'entrance',
    image: {
      url: 'assets/rooms/fatma-semih-akbil-auditorium-wide.png',
      width: 1672,
      height: 941,
      sha256: '75c424a223515a3bd455c6a4c09694db28bd33dcdb472484ecb67da91454ff9c',
    },
    nodes: [
      { id: 'entrance', x: 52, y: 92, z: 0 },
      { id: 'lower-aisle', x: 52, y: 82, z: 0 },
      { id: 'lower-row', x: 62, y: 80, z: 0 },
      { id: 'lower-left-aisle', x: 15, y: 82, z: 0 },
      { id: 'middle-aisle', x: 52, y: 68, z: 0 },
      { id: 'middle-row', x: 62, y: 65, z: 0 },
      { id: 'middle-left-aisle', x: 15, y: 67, z: 0 },
      { id: 'upper-aisle', x: 52, y: 53, z: 0 },
      { id: 'upper-row', x: 62, y: 48, z: 0 },
      { id: 'upper-left-aisle', x: 16, y: 51, z: 0 },
      { id: 'rear-aisle', x: 52, y: 33, z: 0 },
      { id: 'stage-steps', x: 55, y: 29, z: 0 },
      { id: 'stage', x: 72, y: 24, z: 1 },
    ],
    edges: [
      { from: 'entrance', to: 'lower-aisle', kind: 'walk' },
      { from: 'entrance', to: 'lower-left-aisle', kind: 'walk' },
      { from: 'lower-aisle', to: 'lower-row', kind: 'walk' },
      { from: 'lower-aisle', to: 'lower-left-aisle', kind: 'walk' },
      { from: 'lower-aisle', to: 'middle-aisle', kind: 'walk' },
      { from: 'lower-left-aisle', to: 'middle-left-aisle', kind: 'walk' },
      { from: 'middle-aisle', to: 'middle-row', kind: 'walk' },
      { from: 'middle-aisle', to: 'middle-left-aisle', kind: 'walk' },
      { from: 'middle-aisle', to: 'upper-aisle', kind: 'walk' },
      { from: 'middle-left-aisle', to: 'upper-left-aisle', kind: 'walk' },
      { from: 'upper-aisle', to: 'upper-row', kind: 'walk' },
      { from: 'upper-aisle', to: 'upper-left-aisle', kind: 'walk' },
      { from: 'upper-aisle', to: 'rear-aisle', kind: 'walk' },
      { from: 'upper-left-aisle', to: 'rear-aisle', kind: 'walk' },
      { from: 'lower-aisle', to: 'stage-steps', kind: 'walk' },
      { from: 'stage-steps', to: 'stage', kind: 'stair' },
    ],
    seats: [
      { id: 'auditorium-lower', label: 'Lower row', approachNodeId: 'lower-row', sit: { x: 64, y: 79, z: 0 }, facing: 'nw', foregroundMask: null, occlusion: null, foregroundAsset: null },
      { id: 'auditorium-middle', label: 'Middle row', approachNodeId: 'middle-row', sit: { x: 64, y: 64, z: 0 }, facing: 'nw', foregroundMask: null, occlusion: null, foregroundAsset: null },
      { id: 'auditorium-upper', label: 'Upper row', approachNodeId: 'upper-row', sit: { x: 64, y: 47, z: 0 }, facing: 'nw', foregroundMask: null, occlusion: null, foregroundAsset: null },
    ],
    occluders: [],
    actors: {},
  }),
})
